---
title: "Can a Xylophone Play a Dirge? Effects of Timbre on the Categorization of Ambiguous Musical Intervals"
author: "Eva Wu"
output: github_document
---

Advisors: Drs. Howard Nusbaum & Stephen Van Hedger

```{r setup}
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## Hypothesis 

“Happy” instruments would make people more prone to identify the chord as major, 
while “sad” instruments would make people more prone to identify the chord as minor, even without explicitly mentioning associated valence during the task.

## Design

* IV1 (w/in-subject): instrument (Exp1 - xylophone, trumpet, piano, oboe, violin; Exp2 - T1-6 varying in envelope and spectral centroid)

* IV2 (w/in-subject): tuning of middle note (5 levels, in 25c increments)

* IV3 (b/w-subject, exploratory): key (B vs. C) (to find out absolute-pitch-related effects)

* DV: the likelihood that one categorizes a chord as major/minor 

## Procedure

* Pt 1 Sound calibration & headphone test (choose the quietest sound among 3)

* Pt 2 Training (press the buttons to listen to the chords, practice w/ feedback) + 
testing phase (listen to 12 chords and choose b/w major and minor for each, need to correctly answer 8 to pass)

* only analyzed the response of those who passed the assessment w/in 2 tries

* Pt 3 Categorization task (jspsych) - listen to 4 blocks of 70 chords and choose b/w major and minor for each chord; explicit rating of instrument valence at the end

* Pt 4 Questionnaires (demographics & music experience; Qualtrics)

## File directory

* [data_cleaning.md](data_cleaning.md): data cleaning and wrangling 

* [inst-cat-uc-1.csv](inst-cat-uc-1.csv) & [inst-cat-uc-2.csv](inst-cat-uc-2.csv): raw jspsych data concatenated into single csv files

* [qualtrics_cleaned.csv](qualtrics_cleaned.csv): cleaned demographics data

* [data_analysis.md](data_analysis.md): analysis code and results